### ISSUE TITLE
Avoid spawning too many processes

### ISSUE THREAD

**Issue by alainfrisch** [ocaml-omake/omake#15]
Under Windows, spawning a process can be very slow.  I suspect that in a project with many small files, this can represent a large fraction of the build time.

Just to illustrate this fact, a very rough test gives the following timings:
- Calling ocamldep.opt on 60 files sequentially takes about 3.6s on my machine.
- Calling ocamldep.opt once one these 60 files takes about 0.15s.
- Calling ocamldep.opt 60 times without passing it any argument takes about 3.5s.
- The same is true with any executable.

And looking at a few files in a big project, it seems that the cost of calling e.g. ocamlc.opt typically represents more than 15% of its actual work (e.g. 0.2 to compile a module vs 0.03s to call ocamlc.opt without an argument).  If we add the cost of calling ocamldep (which completely dominates its actual work), one might get something like 30% speedup (for bytecode compilation) if one could avoid these calling costs.

Considering these numbers, it would be interesting to extend omake with some machinery to keep external processes alive and reuse them.  For instance, it would be pretty simple to add a mode to ocamldep so that it reads source filenames on it standard input and processes them one by one. omake could spawn a fixed number of such processes (one per omake thread?) and reuse them when needed.  Similarly for ocamlc/ocamlopt.

@gerdstolpmann Does this sound interesting to you?  Do you have an idea how this could be exposed to the omake DSL and how this could be implemented internally?

**Comment by nshibano** [comment]
Hi,

I have checked "Calling ocamldep.opt 60 times without passing it any argument" on my machine, using Powershell.

The test is simple. First, create foo.ps1 with contents as below:
ocamldep.opt
ocamldep.opt
ocamldep.opt
ocamldep.opt
....(same 60 lines)

And measure how long does it take on Powershell.
$ Measure-Command  {.\foo.ps1}

It takes 252 milliseconds. Comparing with Alain's test results, changing the way of calling ocamldep.opt can improve performance.

**Comment by nshibano** [comment]
I have also tested above using OMake.

The test is, create OMakefile with following contents:
.PHONY: foo
foo:
  ocamldep.opt
  ocamldep.opt
  ocamldep.opt
  ...(same 60 lines in total)

And measure it:
Measure-Command {omake foo}

It takes 263 milliseconds. Please note that, because I couldn't build this branch on Windows, the OMake used here is built using ocamlspotter's branch:
https://github.com/camlspotter/omake-fork/commit/25de0395692c1f9bc1f92bf9d54fc1de572a515f

Test environment is:
- Windows10 64bit
- Intel Core i3-6100

**Comment by alainfrisch** [comment]
Indeed!  I tested by calling from Cygwin's bash, which certainly explains the overhead.  I had the feeling that the time spent in dependency analysis for a large OCaml project was rather high and that this would be explained by the cost of calling ocamldep.opt, but I must be wrong.  Perhaps this is the postprocessing done by omake (to map module names to filenames), or the update of the internal dependency graph.  (Or just that the time spent in the dependency analysis is actually not that big compared to the actual build time, I've no strong data to support it except starring at the output of 'omake --no-S').

**Comment by alainfrisch** [comment]
Well, some more realistic data.  In a given directory, after everything has been built, I do: `omake -j 1 all` which triggers no rule and no scan (everything is up to date) and `omake -j 1 --depend all`, which has the effect of forcing 40 dependency scans.  The time moves from 2.05s (reading OMakefiles and cached data, checking that everything is up to date) to 2.70s.  This is about 0.65s for 40 scans.

Now I'm changing the scanner definition to call ocamldep 4 times (and only pipe the last one through ocamldep-postproc) instead of 1.  The time goes from 2.70s to 4.20s.  This suggests that about 0.38s out of the 0.65s are spend in the calls to ocamldep.opt (and its actual processing).  If the 3 extra calls to ocamldep are done with an empty command line, the goes is around 3.5s.  So the pure invocation of ocamldep.opt (with no file to process) seems to take about 0.25s.  This is about what we could gain (out of the 0.65s for the 40 scans) if ocamldep was kept alive by omake.  Now, considering that most of the time is still spend in actual compilation (esp. with ocamlopt), this might not be worth the effort.

**Comment by nshibano** [comment]
Just for information, following is the test results for "omake -j 1 all" and "omake -j 1 all --depend" on already up-to-date OMake source tree, on Cygwin, on my machine.

$ ./omake-boot all -j 1
*** omake: reading OMakefiles
*** omake: finished reading OMakefiles (0.07 sec)
*** omake: done (0.29 sec, 0/245 scans, 0/471 rules, 0/197 digests)

$ ./omake-boot all -j 1 --depend
*** omake: reading OMakefiles
*** omake: finished reading OMakefiles (0.07 sec)
*** omake: done (11.88 sec, 245/245 scans, 0/471 rules, 0/206 digests)

Detailed test command on Cygwin terminal (32 bit):
  git clone https://github.com/nshibano/omake.git
  cd omake
  ocaml -nostdlib -I /usr/lib/ocaml boot.ml
  ./omake-boot all
  ./omake-boot all
  ./omake-boot -j 1 all
  
@alainfrisch  On my environment, "omake -j 1 all" was quite fast. Do you maybe have thousand of files to check stat?

**Comment by gerdstolpmann** [comment]
Well, what we could do is to add a "server mode" to ocamldep/ocamlc/ocamlopt so that you can pipe tasks to stdin (where a task cosists of a cwd and an argv encoding) and get progress messages from stdout (task done with exit code, or a user message - warning or error). This is something we could wire into omake, and it is probably not that difficult as there is already an abstraction for remote servers (remember you can run an omake cluster in the network).

**Comment by alainfrisch** [comment]
> Well, what we could do is to add a "server mode" to ocamldep/ocamlc/ocamlopt so that you can pipe tasks to stdin

Yes, this is exactly what I had in mode.  But it does not seem this would necessarily bring huge gains, considering the discussion above.

It would be interesting to see if ocamlc/ocamlopt could be made better when asked to compile multiple file (today, by passing them together on the command line; tomorrow perhaps through the "server mode").  I might be wrong, but I think that the compiler currently discards previously loaded .cmi files/.cmx files between two compilations.  The time taken to look for those files in the load path (which can be quite long) and then to read+unmarshal them might represent a non-negligible amount of time (to be investigated), and I don't see why this could not be reused across compilations (one argument against doing so is that the "server" process might eat a lot of memory, but this could probably be tweaked).  We have some code that need to read dozens of .cmi files, each of taking a few Mb, so this might be useful.

**Comment by gerdstolpmann** [comment]
The cmi cache would need a different organization. AFAIK currently it is simply a mapping module_name->module_type, and for every extension of the include path the cache needs to be cleared (or you risk that the wrong module is looked up).

A better mapping would be (directory,module_name)->module_type, so that the cache doesn't depend on the include path anymore. The question is how to represent the directory. A simple path doesn't really work when you allow "cd" in server mode. We could use a normalized path (realpath()). That would need an extension of libcamlrun, though, but is generally viable.

Regarding memory consumption, you can drop cache entries that weren't used for some time.

I think there are more ways to save time in server mode, but it's complicated. For example, you could also bundle assembler invocations. Normally, the object files aren't needed immediately, so you could accumulate .s files until the .o is really needed, and then call "as" only once. (Even better: an integrated assembler...)

Not sure how much you get. ocamlopt as such is not the fastest compiler.

**Comment by alainfrisch** [comment]
> (Even better: an integrated assembler...)

We have that, internally (on Windows only), and indeed, it brings a good improvement.

> Do you maybe have thousand of files to check stat?

Yes, this is on a rather large project.
