### ISSUE TITLE
omake can't handle .mli only modules

### ISSUE THREAD

**Issue by rgrinberg** [ocaml-omake/omake#25]
Modules that only have `.ml` and not `.mli` files cannot be used as sources. I've only tested this `$(OCamlLibrary ..)` but it's likely to be a problem with Program/Package as well.

**Comment by gerdstolpmann** [comment]
Don't quite understand what you mean: the title (mli without ml) says the opposite of the text (ml without mli).

Note that mli without ml isn't supported anymore by OCaml (since 4.03).

**Comment by alainfrisch** [comment]
> Note that mli without ml isn't supported anymore by OCaml (since 4.03).

What do you mean?  We still have for instance only parsing/parsetree.mli (no .ml) in the compiler itself.

**Comment by gerdstolpmann** [comment]
After researching, I think I misunderstood that. Only some mli-only cases are no longer supported, namely when there is an external in the mli. But anyway, it is something that might change further - who guarantees that no linking is required for defining any type in the future? Maybe we get some reflection some day, and all types are somehow represented at runtime. It is perhaps not the worst strategy not to support this in a build system, in particular in omake where you can simply define a rule for copying the mli to the ml.

**Comment by Drup** [comment]
> But anyway, it is something that might change further

Who said that ? Because it's going to break a non trivial amount of packages and it's completely unrelated to runtime type reflection anyway.
It's a useful feature that is perfectly well supported by OCaml.

**Comment by gerdstolpmann** [comment]
It's already quite brittle, because there are type definitions that require some minimal RTTI, namely extensible types. So, `type t = X|Y` works mli-only but `type t = <> type t += X|Y` does not (same as exceptions).

I was thinking about adding a macro that compiles the mli as ml, using `ocamlopt -impl file.mli` to provide a little bit more of automation for people who like that, while keeping it easy enough so that you don't need to know the internals of the type representation to use it. That would be simply a call

`DeclareMLIOnly(modules ...)`

and the required flags would be added.

**Comment by gerdstolpmann** [comment]
Found time for an implementation of DeclareMLIOnly.

**Comment by gerdstolpmann** [comment]
DeclareMLIOnly is merged.
