### ISSUE TITLE
"export" isn't sufficient to accumulate values in for loop

### ISSUE THREAD

**Issue by gerdstolpmann** [ocaml-omake/omake#40]
This does not work:
```
private.rebased_lines(filenames) =
        private.l1[] =
        foreach(n => ..., $(filenames))
            private.l2 = $(lines $(n))
            l1 += $(addprefix $(dirname $(n))/, $(l2))
            export l1
        value $(l1)
```
The function returns the value of l1 only from the last loop cycle (as if l1 is reset to the empty array at the beginning of every loop cycle).

**Comment by gerdstolpmann** [comment]
It works when `l1` is not private but public (with dynamic scope). Nevertheless, there is no reason why this shouldn't work for static scope, too.

**Comment by rgrinberg** [comment]
here's a test case showcasing the bug. Note that it can be reproduced on the released version of omake just as well.

```
private.test1(vals) =
  private.l1[] =
  foreach(n => ..., $(vals))
    l1 += $n
    export l1
  value $(l1)

private.test2(vals) =
  l1[] =
  foreach(n => ..., $(vals))
    l1 += $n
    export l1
  value $(l1)


a1[] = one two

v1 = $(test1 $(a1))
v2 = $(test2 $(a1))

println(test v1: $(string $(v1)))
println(test v2: $(string $(v2)))

```

**Comment by gasche** [comment]
I thought this was an amusing problem, so I had a look. It seems to me that this behavior is likely to be correct with respect to the (rather unclear) specification of binding in omake.

Foreach is a higher-function that is passed the function `n => l1 += $n; export l1`. It call this function on all elements of the list, accumulating the results in a result list, and propagating the evaluation environment from the previous return to the next call. In particular, `l1` in `test2` is dynamically-bound variable which start its life as the empty list, the foreach-body is called with the empty list in the environment, it re-exports it as `[one]`, and this exported environment is fed to the foreach-body again that re-exports the result as `[one; two]`.

OMake's implementation of static scoping mandates that, when a function is invoked, the static environment (the part of the evaluation environment that contains the statically-scoped variables) of the invocation is not the static environment of the *call site* (that would be more dynamic), but of the *function definition site*. Technically, the `ValFun` values carry a `env` parameter that is the static environment at their definition.

In `test2`, when the foreach body is called for the first time, it correctly exports `[one]` in its returned environment. But when it is called for the second time, the static environment used is *not* the one of the execution point (the one that saw the `[one]` export), but the one of the foreach-body-definition-point, that had `l1` defined as the empty list.

One can check this assumption by changing the function-application implementation to use the static environment of the call site instead of the definition site (I think this would be the wrong thing to do in general, but let's test it on this example). To do that, one modifies the [ValFun case of Omake_eval.eval_fun](https://github.com/gerdstolpmann/omake/blob/15f10fb/src/eval/omake_eval.ml#L1294-L1301), which currently reads:

```ocaml
and eval_fun venv pos v =
  match eval_value venv pos v with
    ValFun (env, keywords, params, body, export) ->
    let f venv pos loc args kargs =
      let venv_new = Omake_env.venv_add_args venv pos loc env params args keywords kargs in
      let venv_new, result = eval_sequence_exp venv_new pos body in
      let venv = Omake_env.add_exports venv venv_new pos export in
      venv, result
    in
true, f
| ValFunCurry ... -> ...
```

Notice that the environment in which the function body is evaluated is defined as

```ocaml
      let venv_new = Omake_env.venv_add_args venv pos loc env params args keywords kargs in
```

and `venv_add_args` will throw away the static environment of `venv` and use `env` instead (the `static` parameter in the [function definition](https://github.com/gerdstolpmann/omake/blob/15f10fb/src/env/omake_env.ml#L1429)).

To observe the behavior expected on this example (but not in general) it suffices to replace the `env` variable (the function definition's static environment) with the static environment component of the evaluation environment `venv`:

```ocaml
let env = ignore env; Omake_env.venv_get_env venv in
```

the whole `ValFun` case thus modified becomes:

```
    ValFun (env, keywords, params, body, export) ->
      let env = ignore env; Omake_env.venv_get_env venv in
      let f venv pos loc args kargs = ...
```

and you get the expected result.

**Comment by gasche** [comment]
To summarize: for static variables `export` changes the value seen by lookups that are *after* the export statement in the static/syntactic scoping order (the program text that follows). For dynamic variables, `export` changes the value seen by lookups that are after the export in the dynamic program order. This explains the difference of behavior in `foreach` here.

**Comment by gerdstolpmann** [comment]
Gabriel, you are absolutely right with your analysis - I had also some fun this afternoon reading the omake code. I've also tried to fix the problem as follows.

Actually, it is undefined whether the notation `n => ...` really needs to introduce a new function, so my idea is that we change that. We can also see that notation as a parameterized body. The branch `foreach-and-private-vars` extends `ValBody` with the ability to take parameters. The evaluation of the IR term `FunString` (which is, so far I see it, only used for said notation) is changed so that it returns a `ValBody` instead of a `ValFun`. The evaluation is different as `ValBody` takes the caller's environment, and not the environment of the function definition, and because of this the updated values of the static variables are visible.

I haven't checked yet whether this introduces new problems in other corners of the omake DSL.

**Comment by gerdstolpmann** [comment]
PR: https://github.com/gerdstolpmann/omake/pull/42
