### ISSUE TITLE
Option to compile a statically linked version of omake ?

### ISSUE THREAD

**Issue by sbriais** [ocaml-omake/omake#59]
Is there a way to build a statically linked version of omake? 
This would ease deployment of omake in different linux distribution.

**Comment by gerdstolpmann** [comment]
If someone collected popular myths about Linux, this would be my #1 candidate for this list: that static linking solves any problem. On the contrary it creates problems, because a number of libc features depend on dynamic linking.

If you want to create a cross-platform version, just use an old enough version of libc for compiling. Works much better, as libc is carefully maintained and even uses versioned symbols to ensure that a newer version at runtime doesn't cause any problems.

**Comment by rgrinberg** [comment]
What about building omake on alpine linux against [musl](https://www.musl-libc.org/intro.html)? i've never  had the necessity for a truly static binary, so I've never tried it. But it seems promising.

**Comment by sbriais** [comment]
Ok, so if I understand well your answer, I should:
- grab a linux distro with an old libc
- compile a recent version of ocaml on this distro
- compile the dependencies (ncurses, readline, ...)
- compile omake
and then I can redistribute my omake binary?

**Comment by gerdstolpmann** [comment]
sbriais: yes, this is how it works. Regarding the dependencies, you have the option to turn them off (they are all optional), which should only have a mild effect on the usability. Or, you can link them statically (which is tricky - easiest method is to first ensure that they are only available statically, i.e. remove the *.so symlinks while compiling so that only the *.a files are found). Or distribute the shared libraries, and use a wrapper script setting LD_LIBRARY_PATH.

**Comment by sbriais** [comment]
Ok, thanks, I'll try that.
