### ISSUE TITLE
random failure when running on Travis-CI (OCaml 4.04/omake 0.10.1)

### ISSUE THREAD

**Issue by gildor478** [ocaml-omake/omake#66]
See:
https://travis-ci.org/ocaml/oasis/jobs/180239677#L1456

```
*** omake: finished reading OMakefiles (0.15 sec)
- build src/libwithc libwithc.cmxa
+ ocamlmklib -ocamlopt ocamlopt -o libwithc -oc libwithc_stubs p.cmx pc.o
ranlib: './liblibwithc_stubs.a': No such file
*** omake: 154/174 targets are up to date
```

I can restart the very same job and it may succeed.

**Comment by gerdstolpmann** [comment]
In my private builds, I also observe such failures from time to time. Hard to reproduce. No idea yet from where this comes.

**Comment by gerdstolpmann** [comment]
One issue could be identified (https://github.com/ocaml-omake/omake/issues/73), but I don't think this bug has anything to do with it (no packs involved). Generally, random build failures indicate that the dependency graph is incomplete, and because omake runs the compiler several times in parallel this results in race conditions.

I'll check whether this particular tests also suffers from incomplete dependencies.

**Comment by gerdstolpmann** [comment]
I think this is deed the same reason as https://github.com/ocaml-omake/omake/issues/73 but at a different place. If we run ocamlmklib for both byte and native code, we need to make sure that they do not overwrite the files resulting from each other. This can happen when ocamlmklib generates a stub library.

The ocamlmklib call is in the oasis repository. Hence, I created the bug there: https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1739&group_id=54&atid=291

**Comment by gerdstolpmann** [comment]
Apparently not a bug in omake but in the oasis support for omake. Tracking it in the ocamlcore forge (see link above).
