### ISSUE TITLE
Persistent build `-P` does not work in OS X

### ISSUE THREAD

**Issue by camlspotter** [ocaml-omake/omake#77]
This never happens with `omake.0.9.6.8-rc1`.  Even with the simplest `OMakefile` for a single `.ml` file:

```
$ omake  -j1 -P
*** omake: reading OMakefiles
--- Checking for ocamlfind... (found /Users/jun/.opam/4.04.0/bin/ocamlfind)
--- Checking for ocamlc.opt... (found /Users/jun/.opam/4.04.0/bin/ocamlc.opt)
--- Checking for ocamlopt.opt... (found /Users/jun/.opam/4.04.0/bin/ocamlopt.opt)
--- Checking for ocamldep.opt... (found /Users/jun/.opam/4.04.0/bin/ocamldep.opt)
--- Checking for ocamllex.opt... (found /Users/jun/.opam/4.04.0/bin/ocamllex.opt)
--- Checking whether ocamlc understands the "z" warnings... (yes)
--- Checking whether ocamlopt can create cmxs plugins... (yes)
*** omake: finished reading OMakefiles (0.08 sec)
--- Checking if ocamldep understands -modules... (yes)
*** omake: file OMakeroot changed
*** omake: waiting for all jobs to finish
*** omake: a configuration file changed, restarting
*** omake: reading OMakefiles
*** omake: finished reading OMakefiles (0.00 sec)
*** omake: done (0.25 sec, 0/1 scans, 0/5 rules, 0/19 digests)
*** omake: polling for filesystem changes
*** omake: file OMakeroot changed
*** omake: a configuration file changed, restarting
*** omake: reading OMakefiles
...
```

Somehow `omake` thinks `OMakeroot` is changed and loops infinitely.  `omake.0.9.8.6-0.rc1` works fine with the same files.

**Comment by camlspotter** [comment]
OMakefile:
```
FILES[] = a
PROGRAM = program
.DEFAULT: $(OCamlProgram $(PROGRAM), $(FILES))
```

a.ml:
```
let x = 1
```

OMakeroot is the one installed by `omake --install`

**Comment by yutopp** [comment]
Seems `-P` does not work also in Linux... However, behaviour is different from OS X.
In Linux, it seems omake does not detect file changing. Displayed messages are not changed although the files are changed.
```
$ omake  -j1 -P
*** omake: reading OMakefiles
--- Checking for ocamlfind... (found /home/yutopp/.opam/4.04.0/bin/ocamlfind)
--- Checking for ocamlc.opt... (found /home/yutopp/.opam/4.04.0/bin/ocamlc.opt)
--- Checking for ocamlopt.opt... (found /home/yutopp/.opam/4.04.0/bin/ocamlopt.opt)
--- Checking for ocamldep.opt... (found /home/yutopp/.opam/4.04.0/bin/ocamldep.opt)
--- Checking for ocamllex.opt... (found /home/yutopp/.opam/4.04.0/bin/ocamllex.opt)
--- Checking whether ocamlc understands the "z" warnings... (yes)
--- Checking whether ocamlopt can create cmxs plugins... (yes)
*** omake: finished reading OMakefiles (0.10 sec)
*** omake: done (0.20 sec, 1/1 scans, 3/5 rules, 7/43 digests)
*** omake: polling for filesystem changes
```

I used same files as https://github.com/ocaml-omake/omake/issues/77#issuecomment-274365808 for testing.

```
$ uname -osrv
Linux 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 GNU/Linux
$ omake --version
OMake 0.10.1 (development snapshot):\n\tbuild [Mon Jan 23 11:48:08 2017]\n\ton ***

Default library directory : /home/yutopp/.opam/4.04.0/lib/omake
```

Thanks.

**Comment by gerdstolpmann** [comment]
Thanks for pointing this out. My guess is that the modifications of the file cache cause this. The problem with kqueue is that it doesn't report much, and we only monitor for changes of directories. We have to rely on the file cache for filtering out ghost events. So I suspect the endless loop is caused by:
 - we monitor `.` for changes
 - for whatever reason kqueue reports a change (this needs investigation - from a dtruss session I suspect this is `.omakedb` which is written after the monitoring is set up and before the poll)
 - we don't know the files in the directory that changed, so we assume all files in the directory potentially changed (here OMakeroot, OMakefile and a.ml)
 - we rely on the file cache for filtering out false alarms (and I guess this does not work as before)
 - finally, omake assumes all files in the directory have changed, and behaves accordingly

 I need more time for investigation.

**Comment by camlspotter** [comment]
Here is a fix: https://github.com/ocaml-omake/omake/pull/86
